name: Build for macOS

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # - uses: swift-actions/setup-swift@v1
      #   with:
      #     swift-version: "5.8.0"

      # - name: Get swift version
      #   run: swift --version

      - name: Install Tuist
        run: |
          curl -Ls https://install.tuist.io | bash

      - name: Build and package Sensei
        run: |
          make sensei bundle-id-prefix=io.tuist version=0.3.0 build=10
          ls -la
          cp -r ./out/Sensei.app ./Sensei.app
          zip -r Sensei-macOS.zip ./Sensei.app

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Sensei-macOS
          path: Sensei-macOS.zip
